### Create conference
POST http://localhost:8000/conference
Content-Type: application/json
Authorization: Basic am9obmRvZUBnbWFpbC5jb206cXdlcnR5

{
    "title": "Discover Nest.js",
    "seats": 100,
    "startDate": "2024-10-25T10:00:00.000Z",
    "endDate": "2024-10-25T14:00:00.000Z"
}